#include "pio_pwm.h"
#include "pio_pwm.pio.h"   // generated by pioasm at build time
#include "hardware/pio.h"
#include "hardware/gpio.h"
#include <string.h>

// ─── Which GPIO pins use PIO PWM ─────────────────────────────────────────────

static const uint8_t PIO_PINS[] = {10, 11, 13, 25};  // D2-B, D3-B, D7-B, D6-B

bool pio_pwm_pin(uint8_t gpio) {
    for (uint8_t i = 0; i < 4; i++) {
        if (PIO_PINS[i] == gpio) return true;
    }
    return false;
}

// ─── Per-GPIO SM allocation ───────────────────────────────────────────────────

typedef struct {
    PIO  pio;
    uint sm;
    bool claimed;
    bool active;
} PioPwmSlot;

static PioPwmSlot slots[30];   // indexed by GPIO number (GP0–GP29)

static bool pio0_loaded = false;
static bool pio1_loaded = false;
static uint pio0_offset = 0;
static uint pio1_offset = 0;

static uint load_program(PIO p) {
    if (p == pio0) {
        if (!pio0_loaded) {
            pio0_offset = pio_add_program(pio0, &pio_pwm_program);
            pio0_loaded = true;
        }
        return pio0_offset;
    } else {
        if (!pio1_loaded) {
            pio1_offset = pio_add_program(pio1, &pio_pwm_program);
            pio1_loaded = true;
        }
        return pio1_offset;
    }
}

// ─── Public API ───────────────────────────────────────────────────────────────

void pio_pwm_init(uint8_t gpio) {
    if (gpio >= 30 || !pio_pwm_pin(gpio)) return;

    PioPwmSlot *s = &slots[gpio];

    if (!s->claimed) {
        // Allocate a state machine — prefer PIO0, fall back to PIO1.
        int sm = pio_claim_unused_sm(pio0, false);
        if (sm >= 0) {
            s->pio = pio0;
        } else {
            sm = pio_claim_unused_sm(pio1, true);  // panics if none left
            s->pio = pio1;
        }
        s->sm      = (uint)sm;
        s->claimed = true;
    }

    PIO  p      = s->pio;
    uint smn    = s->sm;
    uint offset = load_program(p);

    pio_sm_set_enabled(p, smn, false);
    pio_sm_clear_fifos(p, smn);

    pio_sm_config cfg = pio_pwm_program_get_default_config(offset);
    sm_config_set_sideset_pins(&cfg, gpio);
    pio_sm_init(p, smn, offset, &cfg);

    // Preload ISR with PIO_PWM_WRAP so the period countdown is correct.
    pio_sm_put_blocking(p, smn, PIO_PWM_WRAP);
    pio_sm_exec(p, smn, pio_encode_pull(false, false));
    pio_sm_exec(p, smn, pio_encode_out(pio_isr, 32));

    // Configure pin as PIO-controlled output.
    pio_gpio_init(p, gpio);
    pio_sm_set_consecutive_pindirs(p, smn, gpio, 1, true);

    // Seed the FIFO with "full off" so the first period immediately drives LOW.
    pio_sm_put_blocking(p, smn, PIO_PWM_WRAP + 1u);

    pio_sm_set_enabled(p, smn, true);
    s->active = true;
}

void pio_pwm_set_level(uint8_t gpio, uint16_t level) {
    if (gpio >= 30) return;
    PioPwmSlot *s = &slots[gpio];
    if (!s->active) return;
    // Non-blocking: motor updates at 100 Hz, period is ~50 µs — FIFO won't back up.
    pio_sm_put(s->pio, s->sm, (uint32_t)level);
}

void pio_pwm_stop(uint8_t gpio) {
    if (gpio >= 30) return;
    PioPwmSlot *s = &slots[gpio];
    if (!s->claimed) return;
    pio_sm_set_enabled(s->pio, s->sm, false);
    // Return pin to SIO so the next port type (encoder, GPIO) can claim it.
    gpio_set_function(gpio, GPIO_FUNC_SIO);
    gpio_put(gpio, 0);
    s->active = false;
}
